import Foundation

/// The kind of app the user is dictating into. Mirrors Flow's style categories.
public enum AppCategory: String, Codable, CaseIterable, Sendable, Identifiable {
    case personal, work, email, other
    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .personal: "Personal messages"
        case .work: "Work messages"
        case .email: "Email"
        case .other: "Other"
        }
    }

    public var appExamples: String {
        switch self {
        case .personal: "Messages, WhatsApp, Telegram, Discord, Signal, Instagram"
        case .work: "Slack, Microsoft Teams, LinkedIn, Linear, Notion"
        case .email: "Apple Mail, Outlook, Gmail, Superhuman, Spark"
        case .other: "Notes, Docs, AI assistants, terminals, everything else"
        }
    }

    /// Styles offered for this category, matching Flow ("very casual" is personal-only, "Excited!" isn't personal).
    public var availableStyles: [WritingStyle] {
        switch self {
        case .personal: [.formal, .casual, .veryCasual]
        case .work, .email, .other: [.formal, .casual, .excited]
        }
    }

    public static func category(forBundleID bundleID: String?, appName: String? = nil) -> AppCategory {
        guard let id = bundleID?.lowercased() else { return .other }
        if personalBundleIDs.contains(where: { id.hasPrefix($0) }) { return .personal }
        if workBundleIDs.contains(where: { id.hasPrefix($0) }) { return .work }
        if emailBundleIDs.contains(where: { id.hasPrefix($0) }) { return .email }
        if let name = appName?.lowercased() {
            if ["whatsapp", "telegram", "discord", "signal", "messenger", "messages"].contains(where: name.contains) { return .personal }
            if ["slack", "teams", "linkedin"].contains(where: name.contains) { return .work }
            if ["mail", "outlook", "superhuman", "spark", "airmail", "mimestream"].contains(where: name.contains) { return .email }
        }
        return .other
    }

    static let personalBundleIDs = [
        "com.apple.mobilesms", "com.apple.ichat", "net.whatsapp.whatsapp", "desktop.whatsapp", "whatsapp",
        "ru.keepcoder.telegram", "org.telegram", "com.hnc.discord", "org.whispersystems.signal-desktop",
        "com.facebook.archon", "com.facebook.messenger", "com.burbn.instagram", "com.tinyspeck.slackmacgap.personal",
    ]
    static let workBundleIDs = [
        "com.tinyspeck.slackmacgap", "com.microsoft.teams", "com.microsoft.teams2", "com.linkedin",
        "com.linear", "notion.id", "com.atlassian", "com.figma.desktop", "com.loom",
    ]
    static let emailBundleIDs = [
        "com.apple.mail", "com.microsoft.outlook", "com.superhuman", "com.readdle.smartemail", "com.readdle.spark",
        "it.bloop.airmail", "com.mimestream", "com.google.gmail", "com.fastmail", "com.canarymail", "com.edisonmail",
    ]
}

public enum WritingStyle: String, Codable, CaseIterable, Sendable, Identifiable {
    case formal, casual, veryCasual, excited
    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .formal: "Formal."
        case .casual: "Casual"
        case .veryCasual: "very casual"
        case .excited: "Excited!"
        }
    }

    public var subtitle: String {
        switch self {
        case .formal: "Caps + Punctuation"
        case .casual: "Caps + Less punctuation"
        case .veryCasual: "No Caps + Less punctuation"
        case .excited: "More exclamations"
        }
    }

    /// Short description handed to the AI editor.
    public var promptHint: String {
        switch self {
        case .formal: "Use standard capitalization and full punctuation."
        case .casual: "Use standard capitalization but lighter punctuation: drop the final period of the message."
        case .veryCasual: "Use all lowercase (except the pronoun I and acronyms) and minimal punctuation: no final period."
        case .excited: "Keep the wording, but end sentences with exclamation marks where it fits the tone."
        }
    }

    /// Example rendered in the Style picker, generated by the same formatter the app uses.
    public var example: String {
        StyleFormatter.apply(self, to: "Hey, are you free for lunch tomorrow? Let's do 12 if that works for you.")
    }
}

/// Applies a writing style with deterministic rules (capitalization, punctuation, spacing only — never wording).
public enum StyleFormatter {
    public static func apply(_ style: WritingStyle, to text: String, protectedWords: [String] = []) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return trimmed }
        // Lists and multi-paragraph text keep their structure; only formal/casual rules apply lightly.
        let isStructured = trimmed.contains("\n")
        switch style {
        case .formal:
            return trimmed
        case .casual:
            return isStructured ? trimmed : dropFinalPeriod(trimmed)
        case .veryCasual:
            let lowered = lowercaseSentenceStarts(trimmed, protectedWords: protectedWords)
            return isStructured ? lowered : dropFinalPeriod(lowered)
        case .excited:
            if isStructured { return trimmed }
            var t = trimmed
            if t.hasSuffix(".") && !t.hasSuffix("...") { t.removeLast(); t += "!" }
            return t
        }
    }

    static func dropFinalPeriod(_ text: String) -> String {
        var t = text
        if t.hasSuffix(".") && !t.hasSuffix("...") && !t.hasSuffix("..") {
            // Keep the period of abbreviations like "U.S." or "etc."
            let lastWord = t.split(separator: " ").last.map(String.init) ?? ""
            if lastWord.filter({ $0 == "." }).count == 1 && lastWord.lowercased() != "etc." { t.removeLast() }
        }
        return t
    }

    static func lowercaseSentenceStarts(_ text: String, protectedWords: [String]) -> String {
        let protected = Set(protectedWords.map { $0.lowercased() })
        var words = text.components(separatedBy: " ")
        for i in words.indices {
            let w = words[i]
            guard let first = w.first, first.isUppercase else { continue }
            let core = w.trimmingCharacters(in: .punctuationCharacters)
            if core == "I" || core.hasPrefix("I'") || core.hasPrefix("I’") { continue }
            // Acronyms ("NASA", "API") and mixed case ("iPhone", "McDonald") stay.
            let letters = core.filter(\.isLetter)
            if letters.count > 1 && letters.allSatisfy(\.isUppercase) { continue }
            if letters.dropFirst().contains(where: \.isUppercase) { continue }
            if protected.contains(core.lowercased()) { continue }
            // Only lowercase words at sentence starts; mid-sentence capitals are likely proper nouns.
            let atStart = i == 0 || words[i - 1].hasSuffix(".") || words[i - 1].hasSuffix("!") || words[i - 1].hasSuffix("?") || words[i - 1].hasSuffix("\n")
            if atStart { words[i] = first.lowercased() + w.dropFirst() }
        }
        var result = words.joined(separator: " ")
        // Sentences after newlines.
        result = result.split(separator: "\n", omittingEmptySubsequences: false).map { line -> String in
            guard let f = line.first, f.isUppercase else { return String(line) }
            let firstWord = line.split(separator: " ").first.map(String.init) ?? ""
            let core = firstWord.trimmingCharacters(in: .punctuationCharacters)
            if core == "I" || protected.contains(core.lowercased()) || (core.count > 1 && core.allSatisfy(\.isUppercase)) { return String(line) }
            return f.lowercased() + line.dropFirst()
        }.joined(separator: "\n")
        return result
    }
}
